apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site-deployment
  labels:
    app: static-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - name: static-site-container
        image: manikandaprabu001/app-image:b9e0b17
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
