apiVersion: v1
kind: Service
metadata:
  name: static-site-service
spec:
  type: NodePort
  selector:
    app: static-site
  ports:
    - protocol: TCP
      port: 80          # சர்வீஸின் போர்ட்
      targetPort: 80    # கன்டெய்னரின் போர்ட்
      nodePort: 30080   # பிரவுசரில் பார்க்க உதவும் போர்ட் (30000-32767)
